baseURL = "https://michaelflops.github.io/poliwat/"
languageCode = "en-us"
title = "POLIW.AT"
publishDir = "docs"


theme = "sublime-hugo-theme"

# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
paginate = 50

[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Michael Betts"
	description = "open source thoughts for emotional people"
	copyright = "Omari, SC-LLC"
	avatar = "/images/mike1.png"

	# Custom assets can be linked with their paths relative to static/
	custom_css = []
	custom_js  = []

	# Links to newer/older blog posts
	newer = "Future"
	older = "Past"

	pageNotFoundTitle = "What is lost, will be found."
	pageNotFoundSubtitle = "But it won't be what you lost."

[params.offcanvas]
	# Menu items
	title = "Omari"
	bio2 = "Santa Cruz, CA"
	subscribe = "Help"
	followme = "Contact"

	# Enable Google search
	search_enabled = true
	search = "Look.Up.Squirt.U.Gonna.Die"

	[[params.offcanvas.socialnetworks]]
		name = "michael"
		url = "michaelflops@gmail.com"
